services:
  olist:
    image: postgres:15
    container_name: olist
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olist
    volumes:
      - olist_data:/var/lib/postgresql/data

  received_db:
    image: postgres:15
    container_name: received_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: received_db
    volumes:
      - received_db_data:/var/lib/postgresql/data

volumes:
  olist_data:
  received_db_data: