
CREATE TABLE wide_table (
    sales_id SERIAL PRIMARY KEY,
    order_id VARCHAR(255),
    order_item_id INTEGER,
    customer_id VARCHAR(255),
    customer_unique_id VARCHAR(255),
    customer_zip_code_prefix INTEGER,
    customer_city VARCHAR(255),
    customer_state VARCHAR(50),
    product_id VARCHAR(255),
    product_category_name VARCHAR(255),
    product_name_length INTEGER,
    product_description_length INTEGER,
    product_photos_qty INTEGER,
    product_weight_g INTEGER,
    product_length_cm INTEGER,
    product_height_cm INTEGER,
    product_width_cm INTEGER,
    seller_id VARCHAR(255),
    seller_zip_code_prefix INTEGER,
    seller_city VARCHAR(255),
    seller_state VARCHAR(50),
    seller_lat DECIMAL(8, 6),
    seller_lng DECIMAL(8, 6),
    purchase_date TIMESTAMP,
    order_status VARCHAR(50),
    price DECIMAL(10, 2),
    freight_value DECIMAL(10, 2),
    payment_type VARCHAR(50),
    payment_installments INTEGER,
    payment_value DECIMAL(10, 2),
    review_score INTEGER
);

INSERT INTO wide_table (
    sales_id,
    order_id,
    order_item_id,
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix,
    customer_city,
    customer_state,
    product_id,
    product_category_name,
    product_name_length,
    product_description_length,
    product_photos_qty,
    product_weight_g,
    product_length_cm,
    product_height_cm,
    product_width_cm,
    seller_id,
    seller_zip_code_prefix,
    seller_city,
    seller_state,
    seller_lat,
    seller_lng,
    purchase_date,
    order_status,
    price,
    freight_value,
    payment_type,
    payment_installments,
    payment_value,
    review_score
)
SELECT 
    fs.sales_id,
    fs.order_id,
    fs.order_item_id,
    fs.customer_id,
    dc.customer_unique_id,
    dc.customer_zip_code_prefix,
    dc.customer_city,
    dc.customer_state,
    fs.product_id,
    dp.product_category_name,
    dp.product_name_length,
    dp.product_description_length,
    dp.product_photos_qty,
    dp.product_weight_g,
    dp.product_length_cm,
    dp.product_height_cm,
    dp.product_width_cm,
    fs.seller_id,
    ds.seller_zip_code_prefix,
    ds.seller_city,
    ds.seller_state,
    dg.geolocation_lat AS seller_lat,
    dg.geolocation_lng AS seller_lng,
    fs.purchase_date,
    fs.order_status,
    fs.price,
    fs.freight_value,
    fs.payment_type,
    fs.payment_installments,
    fs.payment_value,
    fs.review_score
FROM 
    fact_sales fs
JOIN 
    dim_customers dc ON fs.customer_id = dc.customer_id
JOIN 
    dim_products dp ON fs.product_id = dp.product_id
JOIN 
    dim_sellers ds ON fs.seller_id = ds.seller_id
JOIN 
    dim_geolocation dg ON ds.seller_zip_code_prefix = dg.zip_code_prefix;
